### ISSUE TITLE
命令词识别准确性有待提高！

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-skainet#1]
- 在 《get_start》 我添加了四个命令词，打开灯( ID0 ) 、关闭灯( ID1 ) 、 打开空调 ( ID2) 、关闭空调 ( ID3 ) ，但是我说  打开空调 都是识别 ID0 , 关闭空调 都是识别为 ID1 ;

- 这个识别有点啥啊！

![image](https://user-images.githubusercontent.com/25237870/66742305-f04d6b00-eea9-11e9-9304-1dfd77d59f6f.png)

![image](https://user-images.githubusercontent.com/25237870/66742321-f8a5a600-eea9-11e9-8855-e4095a7809ac.png)

**Comment by WeldonWangwang** [comment]
谢谢反馈，刚刚已经复现了同样命令词下的情况，确实会出现将“打开空调”对应为“打开灯”，这属于识别完成后对字符解码的一个 bug，由于“打开灯”相较于“打开空调”字符较短，解码出现了问题，我们会近期对其进行更新！
Thanks!

**Comment by WeldonWangwang** [comment]
@xuhongv 您好，该 bug 已经修复，烦请更新 master 分支并更新 submodule 进行再次尝试！
Thanks!

**Comment by xuhongv** [comment]
@WeldonWangwang 大赞，解决速度真快！！！
