### ISSUE TITLE
Support for the Seeed Studio XIAO ESP32C3 (AIS-1205)

### ISSUE THREAD

**Issue by nkeilar** [espressif/esp-skainet#100]
I am wondering of the possibility of running this on the Seeed Studio XIAO ESP32C3 with an INMP441 I2S Microphone. I haven't seen anyone do this - is there a reason for that?

**Comment by feizi** [comment]
ESP32C3 does not support AI instructions， so ESP32C3 cannot run the latest models in real time. We recommend using ESP32S3 chips for AI-related tasks
