### ISSUE TITLE
esp-skainet master分支的cn_speech_commands_recognition语音应答语速过快问题 (AIS-1253)

### ISSUE THREAD

**Issue by Join-qiu** [espressif/esp-skainet#103]
当板子收到唤醒词后，播放的应答语速过快，听不清，请问是哪个地方配置有问题吗？

**Comment by Join-qiu** [comment]
用的是esp32s3开发板

**Comment by feizi** [comment]
应该是codec 的采样率问题，我等下看一下

**Comment by Join-qiu** [comment]
开发板型号：ESP32-S3-Korvo-2
IDF版本：V4.4
测试demo：esp-skainet/examples/cn_speech_commands_recognition

感觉也是codec采样率问题，唤醒词回复播放的是wake_up_prompt_tone数组中的内容，不知道这些数组的内容采样率是多少？

**Comment by Join-qiu** [comment]
esp-skainet版本：master

**Comment by feizi** [comment]
这个问题是由于codec的采样率的问题。
cn_speech_commands_recognition 音频的采样率是8KHz, 我们更新了codec的设置导致里面的默认采样率变为16KHz.
这个bug已经修改了，把默认的codec配置修改为 8KHz了。

**Comment by ZorkyZorky** [comment]
wakenet的I2S传输速率16000hz、32bit/per sample可以改慢一些吗？

**Comment by feizi** [comment]
>16000hz

wakenet 训练的时候输入就是 16kHz, 这个不能修改

> 32bit/per sample

这个是因为 有两个通道（就是两个麦克风数据， 每个是16bit）, 也不能继续减小

**Comment by ZorkyZorky** [comment]
但是esp-box里bsp设置的是16bit/per sample 。有点懵
