### ISSUE TITLE
Using multinet6 without timeout (AIS-1265)

### ISSUE THREAD

**Issue by PrathamG** [espressif/esp-skainet#104]
Hi! I was wondering if it is possible to let the multinet run indefinitely after the wakeword is detected. 

From #81 I found out that the second parameter in 
`multinet->create(mn_name, time_ms)`
is the timeout parameter, which determines how long after the last keyword should the multinet be stopped.

Is there an option to allow the multinet to keep running forever? 
Also, are there any disadvantages to letting the multinet run without timeout?

**Comment by feizi** [comment]
> Is there an option to allow the multinet to keep running forever? Also, are there any disadvantages to letting the multinet run without timeout?

Yes, the second parameter is timeout duration. You can ignore the timeout state when you want to run multinet always.

**Comment by PrathamG** [comment]
Okay got it, thanks!
