### ISSUE TITLE
不使用麦克风进行语音唤醒/识别 (AIS-1292)

### ISSUE THREAD

**Issue by Liuyuehuixue** [espressif/esp-skainet#107]
请问有从TF 卡中的 wav/pcm音频文件进行语音唤醒或识别的示例吗？

**Comment by feizi** [comment]
esp-skianet的性能测试程序是从SD card读文件进行测试的，你可以参考 [wakenet_test](https://github.com/espressif/esp-skainet/blob/master/test/wakenet/main/wakenet_main.c).
