### ISSUE TITLE
esp32-korvo-v1.1 运行识别语音时就会崩溃 (AIS-1451)

### ISSUE THREAD

**Issue by jmdkina** [espressif/esp-skainet#119]
1. 使用 master 分析，编译 cn_speech_commands_recognition 这个demo，直接烧录运行，说 ‘嗨，乐鑫` 识别到后就会崩溃，必现。无源码，无法继续查看
![image](https://github.com/espressif/esp-skainet/assets/3918074/08274e69-2567-4bab-9776-04a3aeeb1a48)

**Comment by feizi** [comment]
请更新一下esp-sr， 再试一下
看这个错误是由于 内存申请不到导致的，问一下你使用的模组是否有PSRAM？

**Comment by jmdkina** [comment]
ESP32-Korvo 这款，直接买的开发板，看说明有 8M psram
换了 esp-sr  1.6.0版本，确实可以了，谢谢
