### ISSUE TITLE
我在开发esp-skainet的垃圾分类例程时，对着麦克风说出命令词没有反应

### ISSUE THREAD

**Issue by lance-web** [espressif/esp-skainet#12]
请教大神如何解决

**Comment by feizi** [comment]
1. 需要先说 “hi，乐鑫”唤醒后，说命令词 
2. 如果不是这个原因，可能是IDF 版本低于V3.3.1，最新的IDF中I2S驱动有修改,当前版本是按照V3.3.1配置，可能导致旧IDF无法正确采集麦克风录音
