### ISSUE TITLE
请教korvo 1.1 主板的多mic设置问题 (AIS-1478)

### ISSUE THREAD

**Issue by Henry586** [espressif/esp-skainet#125]
感觉默认单mic的灵敏度不够，打算设置为双mic,结果不能唤醒了，请问还需要调整哪里呢，
使用的是 nihaoxiaoxin (wn5_nihaoxiaoxinX3)) 模型.

`    afe_config_t afe_config = AFE_CONFIG_DEFAULT();
    //esp32 korvo 1.1
    afe_config.pcm_config.total_ch_num = 3;
    afe_config.pcm_config.mic_num=2;
    afe_config.wakenet_mode = DET_MODE_2CH_90;

`

**Comment by sun-xiangyu** [comment]
Hi @Henry586 ,目前双麦算法不支持ESP32，建议切换到ESP32-S3

**Comment by Henry586** [comment]
Thanks!
