### ISSUE TITLE
Is it possible to create a non-human wake sound (not word)? (AIS-1551)

### ISSUE THREAD

**Issue by gamename** [espressif/esp-skainet#134]
I'm interested in trying to use a cat's meow sound as a "wake word".  Is that possible? 

Thank you,
-T

**Comment by feizi** [comment]
I think it is possible. The key is that we need to collect enough meow sound samples.

**Comment by gamename** [comment]
> I think it is possible. The key is that we need to collect enough meow sound samples.

Great! Is this something I could create on my own?

**Comment by feizi** [comment]
Now we do not open source training pipeline.
If you want to train a model by yourself, I suggest you to search [keyword spotting] in github. You may find some useful project.
