### ISSUE TITLE
bootloader_common.c出现问题，请教大神如何解决

### ISSUE THREAD

**Issue by lance-web** [espressif/esp-skainet#15]
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c: In function 'bootloader_common_ota_select_invalid':
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:50:43: error: 'esp_ota_select_entry_t' {aka 'const struct <anonymous>'} has no member named 'ota_state'; did you mean 'ota_seq'?
     return s->ota_seq == UINT32_MAX || s->ota_state == ESP_OTA_IMG_INVALID || s->ota_state == ESP_OTA_IMG_ABORTED;
                                           ^~~~~~~~~
                                           ota_seq
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:50:56: error: 'ESP_OTA_IMG_INVALID' undeclared (first use in this function); did you mean 'ESP_ERR_IMAGE_INVALID'?
     return s->ota_seq == UINT32_MAX || s->ota_state == ESP_OTA_IMG_INVALID || s->ota_state == ESP_OTA_IMG_ABORTED;
                                                        ^~~~~~~~~~~~~~~~~~~
                                                        ESP_ERR_IMAGE_INVALID
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:50:56: note: each undeclared identifier is reported only once for each function it appears in
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:50:82: error: 'esp_ota_select_entry_t' {aka 'const struct <anonymous>'} has no member named 'ota_state'; did you mean 'ota_seq'?
     return s->ota_seq == UINT32_MAX || s->ota_state == ESP_OTA_IMG_INVALID || s->ota_state == ESP_OTA_IMG_ABORTED;
                                                                                  ^~~~~~~~~
                                                                                  ota_seq
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:50:95: error: 'ESP_OTA_IMG_ABORTED' undeclared (first use in this function); did you mean 'ESP_ERR_NOT_SUPPORTED'?
     return s->ota_seq == UINT32_MAX || s->ota_state == ESP_OTA_IMG_INVALID || s->ota_state == ESP_OTA_IMG_ABORTED;
                                                                                               ^~~~~~~~~~~~~~~~~~~
                                                                                               ESP_ERR_NOT_SUPPORTED
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c: In function 'bootloader_common_get_sha256_of_partition':
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:178:13: error: implicit declaration of function 'esp_image_verify'; did you mean 'esp_image_load'? [-Werror=implicit-function-declaration]
         if (esp_image_verify(ESP_IMAGE_VERIFY_SILENT, &partition_pos, &data) != ESP_OK) {
             ^~~~~~~~~~~~~~~~
             esp_image_load
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:182:38: error: 'esp_image_metadata_t' {aka 'struct <anonymous>'} has no member named 'image_digest'; did you mean 'image_len'?
             memcpy(out_sha_256, data.image_digest, ESP_PARTITION_HASH_LEN);
                                      ^~~~~~~~~~~~
                                      image_len
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c: At top level:
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:244:93: error: unknown type name 'esp_app_desc_t'; did you mean 'esp_chip_id_t'?
 esp_err_t bootloader_common_get_partition_description(const esp_partition_pos_t *partition, esp_app_desc_t *app_desc)
                                                                                             ^~~~~~~~~~~~~~
                                                                                             esp_chip_id_t
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c: In function 'bootloader_common_ota_select_invalid':
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader_support/src/bootloader_common.c:51:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: some warnings being treated as errors
/home/user1/ESP/esp-skainet/esp-idf/make/component_wrapper.mk:285: recipe for target 'src/bootloader_common.o' failed
make[2]: *** [src/bootloader_common.o] Error 1
/home/user1/ESP/esp-skainet/esp-idf/make/project.mk:493: recipe for target 'component-bootloader_support-build' failed
make[1]: *** [component-bootloader_support-build] Error 2
/home/user1/ESP/esp-skainet/esp-idf/components/bootloader/Makefile.projbuild:41: recipe for target '/home/user1/ESP/esp/esp-skainet/esp-idf/examples/get-started/hello_world/build/bootloader/bootloader.bin' failed
make: *** [/home/user1/ESP/esp/esp-skainet/esp-idf/examples/get-started/hello_world/build/bootloader/bootloader.bin] Error 2

**Comment by feizi** [comment]
如果你没有修改IDF代码，那大概率是IDF版本和skainet不匹配造成，建议切换到指定的IDF版本
