### ISSUE TITLE
examples\chinese_tts  速率 不对  播放的时候快了两倍

### ISSUE THREAD

**Issue by tongjinlv** [espressif/esp-skainet#23]
examples\chinese_tts  速率 不对  播放的时候快了两倍

**Comment by feizi** [comment]
重复测试了一遍，语速没有问题
1. 检测esp_tts_stream_play中最后一个参数，该参数用于调节语速
2. 使用sdcard测试，将example/chinese_tts/main/main.c第22行的注释打开，将合成的语音保存在sdcard中，如果保存的音频没有问题，应该是codec的设置有问题

**Comment by Gallium70** [comment]
用i2s输出的时候把每个数据都复制一遍，比如1 3 5复制成1 1 3 3 5 5，不然有可能数据被分到两个声道里去了

**Comment by aqibluesky** [comment]
是的。默认的例程，用lyrat语速是快了，开到最低速度也是快

**Comment by feizi** [comment]
如果选择Lyrat_v4.3,   是会出现语速加快，因为该开发板默认的I2S播放是双声道的，可以按照 @Gallium70 的方法修改
其他板子lyrat_mini和korvo的播放默认设置是单声道，不需要修改

**Comment by feizi** [comment]
该bug已经修改
