### ISSUE TITLE
get_started 项目不能在（ESP32-Korvo-DU1906开发板）上正常运行

### ISSUE THREAD

**Issue by 1003657663** [espressif/esp-skainet#27]
### ESP32-Korvo-DU1906开发板（error）

![image](https://user-images.githubusercontent.com/6650078/99910639-1fc7db80-2d2a-11eb-9997-2daa13f9ff10.png)

version: idf-3.3.1   这是对应的报错信息，并且在反复rebooting，然后报出这个错误。

另外

idf-4.0.2和idf-4.1都无法运行，并且无限rebooting

**Comment by feizi** [comment]
esp-skainet默认没有esp32-korvo-DU1906的硬件驱动, 可以参考ESP-ADF中esp32-korvo-DU1906的驱动设置移植到esp-skainet
