### ISSUE TITLE
get_started例程不能再lyrat-mini-v1.2上正常运行

### ISSUE THREAD

**Issue by qpmc1s** [espressif/esp-skainet#28]
Quantized wakeNet5: wakeNet5_v1_hilexin_5_0.95_0.90, mode:0 (Oct 14 2020 16:26:17)
CONTINUOUS_RECOGNITION: 2_0 MN1_4; core: 0; (May 15 2020 14:50:28)
SHIFT: 8, 12, 17, 17, 19, 17, 6, 16, 15, 14, 
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0)
Core 0 register dump:
PC      : 0x40081a6e  PS      : 0x00060c35  A0      : 0x800864c2  A1      : 0x3ffb4d40  
A2      : 0x00000000  A3      : 0x00060c20  A4      : 0x3ff00058  A5      : 0x3ffb4d68  
A6      : 0x00060c20  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x00000001  
A10     : 0x00000000  A11     : 0x3ffb50cc  A12     : 0x00000001  A13     : 0x00000001  
A14     : 0x00060c23  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x4008d691  LEND    : 0x4008d6a1  LCOUNT  : 0xfffffffd  

ELF file SHA256: 

Backtrace: 0x40081a6e:0x3ffb4d40 0x400864bf:0x3ffb4d60 0x4008655f:0x3ffb4db0 0x400f67c1:0x3ffb4de0 0x400f6982:0x3ffb4e10 0x400f69d3:0x3ffb4e30 0x400ee8c8:0x3ffb4e50 0x400edbaa:0x3ffb4e70 0x400eddfa:0x3ffb4fc0 0x400d65b0:0x3ffb4ff0 0x400d1958:0x3ffb5020 0x40089cbd:0x3ffb5040

**Comment by feizi** [comment]
我用lyrat-mini-v1.2测试，没有复现你的问题。
你可以尝试将build文件夹删除，同时将sdkconfig和sdkconfig.old删除，重新编译尝试一下
