### ISSUE TITLE
Request to run on other ESP32 boards

### ISSUE THREAD

**Issue by plofski** [espressif/esp-skainet#29]
Is it possible to create an arduino library from skainet and run it on other esp32 boards? I currently have a esp-wroom-32 with an SD card connected to it, is there any way to run skainet on it and turn on / off GPIO's ?

**Comment by feizi** [comment]
If you want to use esp-wroom-32, I recommend you to use [esp-sr](https://github.com/espressif/esp-sr), which can be used as a component of your project and does not use GPIO.
