### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by Fusion-Pie** [espressif/esp-skainet#33]
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
CMake Error at C:/Users/HP/esp/esp-idf/tools/cmake/build.cmake:189 (message):
  Failed to resolve component 'esp-sr'.
Call Stack (most recent call first):
  C:/Users/HP/esp/esp-idf/tools/cmake/build.cmake:215 (__build_resolve_and_add_req)
  C:/Users/HP/esp/esp-idf/tools/cmake/build.cmake:435 (__build_expand_requirements)
  C:/Users/HP/esp/esp-idf/tools/cmake/project.cmake:396 (idf_build_process)
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/HP/esp/voice

**Comment by feizi** [comment]
Please try new examples
