### ISSUE TITLE
can not be waked up after complie /esp-skainet/example/get_started 

### ISSUE THREAD

**Issue by mnescola** [espressif/esp-skainet#34]
burning the default factory firmware (ESP skainet / tools / default_firmware / esp32_korvo_v1_fw_v0_1_20200323. Bin), supporting voice wake-up and light color control.
I compiled and burned the sample project ESP skainet / examples / get_ Started, there are the following problems:

can not be waked up

**Comment by feizi** [comment]
Pls try examples/en_speech_commands_recognition
