### ISSUE TITLE
undefined references to `xQueueGenericReceive' (AIS-743)

### ISSUE THREAD

**Issue by FRANCISEG** [espressif/esp-skainet#36]
/home/winter/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/winter/item/esp-skainet/components/esp-sr/lib/esp32/libdl_lib.a(sr_ringbuf.c.obj):(.literal.sr_rb_read+0x0): undefined reference to `xQueueGenericReceive'
/home/winter/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/winter/item/esp-skainet/components/esp-sr/lib/esp32/libdl_lib.a(sr_ringbuf.c.obj): in function `sr_rb_read':
/home/wangwangwang/workspace/ai_vnc/728_support/esp_sr_lib_tmp3/build/../components/dl_lib/sr_ringbuf.c:101: undefined reference to `xQueueGenericReceive'
/home/winter/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/wangwangwang/workspace/ai_vnc/728_support/esp_sr_lib_tmp3/build/../components/dl_lib/sr_ringbuf.c:136: undefined reference to `xQueueGenericReceive'
/home/winter/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/wangwangwang/workspace/ai_vnc/728_support/esp_sr_lib_tmp3/build/../components/dl_lib/sr_ringbuf.c:148: undefined reference to `xQueueGenericReceive'
/home/winter/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/winter/item/esp-skainet/components/esp-sr/lib/esp32/libdl_lib.a(sr_ringbuf.c.obj): in function `sr_rb_write':
/home/wangwangwang/workspace/ai_vnc/728_support/esp_sr_lib_tmp3/build/../components/dl_lib/sr_ringbuf.c:167: undefined reference to `xQueueGenericReceive'
/home/winter/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/winter/item/esp-skainet/components/esp-sr/lib/esp32/libdl_lib.a(sr_ringbuf.c.obj):/home/wangwangwang/workspace/ai_vnc/728_support/esp_sr_lib_tmp3/build/../components/dl_lib/sr_ringbuf.c:202: more undefined references to `xQueueGenericReceive' follow

**Comment by WeldonWangwang** [comment]
Hi, @FRANCISEG Which version and branch of ESP-IDF do you use?  Esp-skainet support IDFV4.4(https://github.com/espressif/esp-idf/tree/release/v4.4) now.
