### ISSUE TITLE
Several links in project README.md are broken (AIS-784)

### ISSUE THREAD

**Issue by iammeat** [espressif/esp-skainet#39]
While browsing the documentation, I found the following links are broken in README.md:

**Wake Word Engine paragraph:**
WakeNet
Espressif Speech Wake Words Customization Process

**Speech Commands Recognition paragraph:**
MultiNet

**ESP-IDF in the Software Preparation section:**
Getting Started Guide for the stable ESP-IDF version

**Comment by feizi** [comment]
Thank you for your reminder, we will fix it.

**Comment by aderusha** [comment]
Submitted PR #40 : https://github.com/espressif/esp-skainet/pull/40
