### ISSUE TITLE
ESP32-LyraT V4.3 No longer supported?  (AIS-842)

### ISSUE THREAD

**Issue by aswinda29** [espressif/esp-skainet#44]
I have been using ESP-Skainet with the lyraT board. In the new commits I see that the examples are no longer supported in this board. Is there a work around?

**Comment by feizi** [comment]
I'm sorry that LyratV4.3 is no longer supported. If you want to use it, you can refer to the examples in ESP-ADF.
Generally, the performance of ESP32S3 on AI-related tasks is 5~10 times that of ESP32. Many new algorithms can only be run on the ESP32-S3 board.
we strongly recommend you move to the ESP32-S3 board.

**Comment by Phil-f6czv** [comment]
Hello
I developped In July 2021 an application on LyraT 4.3 and Skainet with English commands. I did not see yesterday that the LyraT was no longer supported and I upgraded the IDF and the Skainet. Is it possible to get the July 2021Skainet version ?
Regards
Philippe

**Comment by feizi** [comment]
We highly recommend you switch to esp32-s3 for English commands applications
