### ISSUE TITLE
自定义语音命令

### ISSUE THREAD

**Issue by Tflgit** [espressif/esp-skainet#5]
在README里：
用户可方便根据需求自定义语音命令，无需重新训练模型。
目前模型支持类似“打开空调”，“打开卧室灯”等中文命令词识别。
类似“打开空调”，“打开卧室灯”等命令词具体是怎样的？

**Comment by WeldonWangwang** [comment]
只要是常见汉语词组或短句，且整个正常读音长度不超过识别接口允许的最长时间 6s 即可。

**Comment by Tflgit** [comment]
OK。语音识别接口最长时间是6s是硬件参数还是软件参数？是否可改？

**Comment by WeldonWangwang** [comment]
是软件参数，调节范围为（0～6000] ms

**Comment by Tflgit** [comment]
好的，谢谢
