### ISSUE TITLE
esp32 s3 + MIC for offline speech recognition (AIS-873)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-skainet#50]
你好，想要通过 [ESP32-S3-DevKitC-1R8N8](https://item.taobao.com/item.htm?spm=a1z0d.6639537.1997196601.13.50d77484Z3T2yQ&id=653155344338) 开发板 和 [GY-SPH0645LM4H数字麦克风](https://item.taobao.com/item.htm?spm=a230r.1.14.1.2ad939962mbhw8&id=629956038542&ns=1&abbucket=1#detail)实现离线语音识别，想确定下这个sdk是否适用

**Comment by WeldonWangwang** [comment]
你好，这个SDK 不能直接支持您的硬件，不过，您可以参考 [ESP-EYE](https://github.com/espressif/esp-skainet/blob/master/components/hardware_driver/boards/include/esp32_s3_eye_board.h) 的驱动，仅仅修改 I2S 部分，便可以支持您的应用。
