### ISSUE TITLE
下面这个demo是如何支持esp32 box lite的，试了没有效果 (AIS-874)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-skainet#51]
https://github.com/espressif/esp-skainet/tree/master/examples/cn_speech_commands_recognition

**Comment by WeldonWangwang** [comment]
你好，目前 Skainet 支持的硬件为 https://github.com/espressif/esp-skainet#hardware-preparation， 目前还不支持 ESP-BOX-Lite，不过我们会最近添加对 ESP-BOX-Lite 的支持。
如果您急需使用，可以先使用[ ESP-BOX](https://github.com/espressif/esp-box)，这个仓库除了语音外加入了其他功能支持。
