### ISSUE TITLE
基于官方的2.0.3SDK,在Arduino上运行，能够唤醒，指令无法识别 (AIS-881)

### ISSUE THREAD

**Issue by tangjie133** [espressif/esp-skainet#54]
问题如题，基于官方的2.0.3SDK在Arduino上运行，唤醒词能够识别，但是指令词无法识别。
烧录如下：

> C:\Users\tangjie\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.3.0/esptool.exe --chip esp32s3 --port COM9 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0 C:\Users\tangjie\AppData\Local\Temp\arduino_build_885412/wakeWordDetection.ino.bootloader.bin 0x8000 C:\Users\tangjie\AppData\Local\Temp\arduino_build_885412/wakeWordDetection.ino.partitions.bin 0x10000 C:\Users\tangjie\AppData\Local\Temp\arduino_build_885412/wakeWordDetection.ino.bin 0x281000 C:\Users\tangjie\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.3/tools/sdk/esp32s3/bin/model.bin 
esptool.py v3.3
Serial port COM9
Connecting...
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 68:b6:b3:22:13:20
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00000000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x00010000 to 0x000b3fff...
Flash will be erased from 0x00281000 to 0x0078cfff...
Compressed 22208 bytes to 13805...
Writing at 0x00000000... (100 %)
Wrote 22208 bytes (13805 compressed) at 0x00000000 in 0.5 seconds (effective 391.6 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 121...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (121 compressed) at 0x00008000 in 0.0 seconds (effective 519.9 kbit/s)...
Hash of data verified.
Compressed 668992 bytes to 357539...
Writing at 0x00010000... (4 %)
Writing at 0x0001a52a... (9 %)
Writing at 0x00026c93... (13 %)
Writing at 0x00039cb1... (18 %)
Writing at 0x00040fbf... (22 %)
Writing at 0x00046ca1... (27 %)
Writing at 0x0004c49b... (31 %)
Writing at 0x00051469... (36 %)
Writing at 0x00056617... (40 %)
Writing at 0x0005b57b... (45 %)
Writing at 0x00060be1... (50 %)
Writing at 0x00066322... (54 %)
Writing at 0x0006bf47... (59 %)
Writing at 0x00073afa... (63 %)
Writing at 0x0007bab3... (68 %)
Writing at 0x0008304f... (72 %)
Writing at 0x00088715... (77 %)
Writing at 0x0008e8be... (81 %)
Writing at 0x00096967... (86 %)
Writing at 0x0009d95b... (90 %)
Writing at 0x000a6a68... (95 %)
Writing at 0x000ae736... (100 %)
Wrote 668992 bytes (357539 compressed) at 0x00010000 in 7.4 seconds (effective 720.6 kbit/s)...
Hash of data verified.
Compressed 5292032 bytes to 2127378...
Writing at 0x00281000... (0 %)
Writing at 0x00285ee9... (1 %)
Writing at 0x0028acc2... (2 %)
Writing at 0x0028fa56... (3 %)
Writing at 0x002948c0... (3 %)
Writing at 0x002996e4... (4 %)
Writing at 0x0029df59... (5 %)
Writing at 0x002a2802... (6 %)
Writing at 0x002a6f9e... (6 %)
Writing at 0x002ab833... (7 %)
Writing at 0x002b0133... (8 %)
Writing at 0x002b4a18... (9 %)
Writing at 0x002b93e4... (10 %)
Writing at 0x002bdce9... (10 %)
Writing at 0x002c26e8... (11 %)
Writing at 0x002c71f4... (12 %)
Writing at 0x002cbc3e... (13 %)
Writing at 0x002d07a5... (13 %)
Writing at 0x002d530a... (14 %)
Writing at 0x002d9d54... (15 %)
Writing at 0x002de9a2... (16 %)
Writing at 0x002e36a6... (16 %)
Writing at 0x002e83c0... (17 %)
Writing at 0x002ecfda... (18 %)
Writing at 0x002f1ced... (19 %)
Writing at 0x002f6993... (20 %)
Writing at 0x002fb5a2... (20 %)
Writing at 0x003001a1... (21 %)
Writing at 0x00304c9f... (22 %)
Writing at 0x00309871... (23 %)
Writing at 0x0030e4ab... (23 %)
Writing at 0x003131c5... (24 %)
Writing at 0x00317eef... (25 %)
Writing at 0x0031ccbe... (26 %)
Writing at 0x00321b31... (26 %)
Writing at 0x003269a6... (27 %)
Writing at 0x0032b7ed... (28 %)
Writing at 0x0033038a... (29 %)
Writing at 0x00334de4... (30 %)
Writing at 0x0033994b... (30 %)
Writing at 0x0033e4b0... (31 %)
Writing at 0x00342f06... (32 %)
Writing at 0x00347b03... (33 %)
Writing at 0x0034c882... (33 %)
Writing at 0x003515aa... (34 %)
Writing at 0x0035634c... (35 %)
Writing at 0x0035afcb... (36 %)
Writing at 0x0035fcab... (36 %)
Writing at 0x00364b72... (37 %)
Writing at 0x00369a50... (38 %)
Writing at 0x0036e970... (39 %)
Writing at 0x0037388e... (40 %)
Writing at 0x003787de... (40 %)
Writing at 0x0037d8b4... (41 %)
Writing at 0x00382aa4... (42 %)
Writing at 0x00387d64... (43 %)
Writing at 0x0038cfbc... (43 %)
Writing at 0x0039230c... (44 %)
Writing at 0x003972b2... (45 %)
Writing at 0x0039be32... (46 %)
Writing at 0x003a0b55... (46 %)
Writing at 0x003a588d... (47 %)
Writing at 0x003aa5a2... (48 %)
Writing at 0x003af295... (49 %)
Writing at 0x003b42eb... (50 %)
Writing at 0x003b9442... (50 %)
Writing at 0x003be4f3... (51 %)
Writing at 0x003c35e4... (52 %)
Writing at 0x003c86d2... (53 %)
Writing at 0x003cceef... (53 %)
Writing at 0x003d1805... (54 %)
Writing at 0x003d6366... (55 %)
Writing at 0x003daec8... (56 %)
Writing at 0x003dfb96... (56 %)
Writing at 0x003e46ef... (57 %)
Writing at 0x003e9202... (58 %)
Writing at 0x003edbc4... (59 %)
Writing at 0x003f264e... (60 %)
Writing at 0x003f6fd2... (60 %)
Writing at 0x003fbad7... (61 %)
Writing at 0x0040077d... (62 %)
找到无效库在 H:\Arduino\libraries\esp32_SoundRecorder: no headers files (.h) found in H:\Arduino\libraries\esp32_SoundRecorder
Writing at 0x00405341... (63 %)
Writing at 0x00409c1c... (63 %)
Writing at 0x0040e6a5... (64 %)
Writing at 0x00413152... (65 %)
Writing at 0x00417cbc... (66 %)
Writing at 0x0041cb08... (66 %)
Writing at 0x00421b4a... (67 %)
Writing at 0x00426cd2... (68 %)
Writing at 0x0042bb2d... (69 %)
Writing at 0x004309a2... (70 %)
Writing at 0x00435777... (70 %)
Writing at 0x0043a4b8... (71 %)
Writing at 0x0043efbd... (72 %)
Writing at 0x00443d21... (73 %)
Writing at 0x00448c70... (73 %)
Writing at 0x0044d905... (74 %)
Writing at 0x004524d9... (75 %)
Writing at 0x00456f97... (76 %)
Writing at 0x0045ba90... (76 %)
Writing at 0x00461f6d... (77 %)
Writing at 0x00467e94... (78 %)
Writing at 0x0046ddf7... (79 %)
Writing at 0x00473e4d... (80 %)
Writing at 0x0047a103... (80 %)
Writing at 0x004804b3... (81 %)
Writing at 0x004866de... (82 %)
Writing at 0x0048c974... (83 %)
Writing at 0x00492a06... (83 %)
Writing at 0x004989ad... (84 %)
Writing at 0x0049e9a5... (85 %)
Writing at 0x004a4b81... (86 %)
Writing at 0x004aad2a... (86 %)
Writing at 0x004b0e78... (87 %)
Writing at 0x004b7114... (88 %)
Writing at 0x004bd2b2... (89 %)
Writing at 0x004c33e2... (90 %)
Writing at 0x004c95d7... (90 %)
Writing at 0x004cf6f7... (91 %)
Writing at 0x004d5a62... (92 %)
Writing at 0x004dbef0... (93 %)
Writing at 0x004e22b9... (93 %)
Writing at 0x004e92b2... (94 %)
Writing at 0x004efc70... (95 %)
Writing at 0x004f6719... (96 %)
Writing at 0x004ff64b... (96 %)
Writing at 0x0050778b... (97 %)
Writing at 0x00510bfe... (98 %)
Writing at 0x005227e6... (99 %)
Writing at 0x0053225c... (100 %)
Wrote 5292032 bytes (2127378 compressed) at 0x00281000 in 46.6 seconds (effective 908.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
运行

> Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x40378b31
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x178c
load:0x403b6000,len:0xe28
load:0x403ba000,len:0x30b8
entry 0x403b6274
[0;32mI (28) boot: ESP-IDF v4.4 2nd stage bootloader[0m
[0;32mI (28) boot: compile time 16:32:36[0m
[0;32mI (28) boot: chip revision: 0[0m
[0;32mI (29) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (35) boot.esp32s3: Boot SPI Speed : 80MHz[0m
[0;32mI (39) boot.esp32s3: SPI Mode       : QIO[0m
[0;32mI (44) boot.esp32s3: SPI Flash Size : 8MB[0m
[0;32mI (49) boot: Enabling RNG early entropy source...[0m
[0;32mI (54) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00005000[0m
[0;32mI (72) boot:  1 otadata          OTA data         01 00 0000e000 00002000[0m
[0;32mI (80) boot:  2 factory          factory app      00 00 00010000 00271000[0m
[0;32mI (87) boot:  3 model            Unknown data     01 82 00281000 0050c000[0m
[0;32mI (95) boot: End of partition table[0m
[0;32mI (99) boot: Defaulting to factory image[0m
[0;32mI (104) esp_image: segment 0: paddr=00010020 vaddr=3c070020 size=26dd0h (159184) map[0m
[0;32mI (136) esp_image: segment 1: paddr=00036df8 vaddr=3fc97290 size=02a44h ( 10820) load[0m
[0;32mI (139) esp_image: segment 2: paddr=00039844 vaddr=40374000 size=067d4h ( 26580) load[0m
[0;32mI (147) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=66a2ch (420396) map[0m

[16:43:00.246]收←◆[0;32mI (214) esp_image: segment 4: paddr=000a6a54 vaddr=4037a7d4 size=0cab0h ( 51888) load[0m
[0;32mI (225) esp_image: segment 5: paddr=000b350c vaddr=50000000 size=00010h (    16) load[0m
[0;32mI (232) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (232) boot: Disabling RNG early entropy source...[0m
[   252][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
Initializing SPIFFS

[16:43:00.633]收←◆Partition size: total: 4857101, used: 2629225

[16:43:00.679]收←◆model_name: xiaoaitongxue7q8 model_data: /srmodel/xiaoaitongxue7q8/wn7q8_data

[16:43:01.513]收←◆MC Quantized-8 wakeNet7: wakeNet7Q8_v1_xiaoaitongxue_5_0.97_0.90, mode:2, p:3, (Jan  5 2022 11:31:01)
Initial ONE-MIC auido front-end for speech recognition, mode:0, (Dec 10 2021 11:08:01)

[16:43:04.129]收←◆------------detect start------------

[16:44:06.602]收←◆wakeword detected
-----------LISTENING-----------

[16:44:17.908]收←◆
-----------awaits to be waken up-----------
请问这会是什么问题导致的呢？

**Comment by feizi** [comment]
看你的log，Multinet(也就是命令词) 都没有初始化

**Comment by feizi** [comment]
> 问题如题，基于官方的2.0.3SDK在Arduino上运行，唤醒词能够识别，但是指令词无法识别。 烧录如下：
> 
> > C:\Users\tangjie\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.3.0/esptool.exe --chip esp32s3 --port COM9 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0 C:\Users\tangjie\AppData\Local\Temp\arduino_build_885412/wakeWordDetection.ino.bootloader.bin 0x8000 C:\Users\tangjie\AppData\Local\Temp\arduino_build_885412/wakeWordDetection.ino.partitions.bin 0x10000 C:\Users\tangjie\AppData\Local\Temp\arduino_build_885412/wakeWordDetection.ino.bin 0x281000 C:\Users\tangjie\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.3/tools/sdk/esp32s3/bin/model.bin
> > esptool.py v3.3
> > Serial port COM9
> > Connecting...
> > Chip is ESP32-S3
> > Features: WiFi, BLE
> > Crystal is 40MHz
> > MAC: 68:b6:b3:22:13:20
> > Uploading stub...
> > Running stub...
> > Stub running...
> > Changing baud rate to 921600
> > Changed.
> > Configuring flash size...
> > Flash will be erased from 0x00000000 to 0x00005fff...
> > Flash will be erased from 0x00008000 to 0x00008fff...
> > Flash will be erased from 0x00010000 to 0x000b3fff...
> > Flash will be erased from 0x00281000 to 0x0078cfff...
> > Compressed 22208 bytes to 13805...
> > Writing at 0x00000000... (100 %)
> > Wrote 22208 bytes (13805 compressed) at 0x00000000 in 0.5 seconds (effective 391.6 kbit/s)...
> > Hash of data verified.
> > Compressed 3072 bytes to 121...
> > Writing at 0x00008000... (100 %)
> > Wrote 3072 bytes (121 compressed) at 0x00008000 in 0.0 seconds (effective 519.9 kbit/s)...
> > Hash of data verified.
> > Compressed 668992 bytes to 357539...
> > Writing at 0x00010000... (4 %)
> > Writing at 0x0001a52a... (9 %)
> > Writing at 0x00026c93... (13 %)
> > Writing at 0x00039cb1... (18 %)
> > Writing at 0x00040fbf... (22 %)
> > Writing at 0x00046ca1... (27 %)
> > Writing at 0x0004c49b... (31 %)
> > Writing at 0x00051469... (36 %)
> > Writing at 0x00056617... (40 %)
> > Writing at 0x0005b57b... (45 %)
> > Writing at 0x00060be1... (50 %)
> > Writing at 0x00066322... (54 %)
> > Writing at 0x0006bf47... (59 %)
> > Writing at 0x00073afa... (63 %)
> > Writing at 0x0007bab3... (68 %)
> > Writing at 0x0008304f... (72 %)
> > Writing at 0x00088715... (77 %)
> > Writing at 0x0008e8be... (81 %)
> > Writing at 0x00096967... (86 %)
> > Writing at 0x0009d95b... (90 %)
> > Writing at 0x000a6a68... (95 %)
> > Writing at 0x000ae736... (100 %)
> > Wrote 668992 bytes (357539 compressed) at 0x00010000 in 7.4 seconds (effective 720.6 kbit/s)...
> > Hash of data verified.
> > Compressed 5292032 bytes to 2127378...
> > Writing at 0x00281000... (0 %)
> > Writing at 0x00285ee9... (1 %)
> > Writing at 0x0028acc2... (2 %)
> > Writing at 0x0028fa56... (3 %)
> > Writing at 0x002948c0... (3 %)
> > Writing at 0x002996e4... (4 %)
> > Writing at 0x0029df59... (5 %)
> > Writing at 0x002a2802... (6 %)
> > Writing at 0x002a6f9e... (6 %)
> > Writing at 0x002ab833... (7 %)
> > Writing at 0x002b0133... (8 %)
> > Writing at 0x002b4a18... (9 %)
> > Writing at 0x002b93e4... (10 %)
> > Writing at 0x002bdce9... (10 %)
> > Writing at 0x002c26e8... (11 %)
> > Writing at 0x002c71f4... (12 %)
> > Writing at 0x002cbc3e... (13 %)
> > Writing at 0x002d07a5... (13 %)
> > Writing at 0x002d530a... (14 %)
> > Writing at 0x002d9d54... (15 %)
> > Writing at 0x002de9a2... (16 %)
> > Writing at 0x002e36a6... (16 %)
> > Writing at 0x002e83c0... (17 %)
> > Writing at 0x002ecfda... (18 %)
> > Writing at 0x002f1ced... (19 %)
> > Writing at 0x002f6993... (20 %)
> > Writing at 0x002fb5a2... (20 %)
> > Writing at 0x003001a1... (21 %)
> > Writing at 0x00304c9f... (22 %)
> > Writing at 0x00309871... (23 %)
> > Writing at 0x0030e4ab... (23 %)
> > Writing at 0x003131c5... (24 %)
> > Writing at 0x00317eef... (25 %)
> > Writing at 0x0031ccbe... (26 %)
> > Writing at 0x00321b31... (26 %)
> > Writing at 0x003269a6... (27 %)
> > Writing at 0x0032b7ed... (28 %)
> > Writing at 0x0033038a... (29 %)
> > Writing at 0x00334de4... (30 %)
> > Writing at 0x0033994b... (30 %)
> > Writing at 0x0033e4b0... (31 %)
> > Writing at 0x00342f06... (32 %)
> > Writing at 0x00347b03... (33 %)
> > Writing at 0x0034c882... (33 %)
> > Writing at 0x003515aa... (34 %)
> > Writing at 0x0035634c... (35 %)
> > Writing at 0x0035afcb... (36 %)
> > Writing at 0x0035fcab... (36 %)
> > Writing at 0x00364b72... (37 %)
> > Writing at 0x00369a50... (38 %)
> > Writing at 0x0036e970... (39 %)
> > Writing at 0x0037388e... (40 %)
> > Writing at 0x003787de... (40 %)
> > Writing at 0x0037d8b4... (41 %)
> > Writing at 0x00382aa4... (42 %)
> > Writing at 0x00387d64... (43 %)
> > Writing at 0x0038cfbc... (43 %)
> > Writing at 0x0039230c... (44 %)
> > Writing at 0x003972b2... (45 %)
> > Writing at 0x0039be32... (46 %)
> > Writing at 0x003a0b55... (46 %)
> > Writing at 0x003a588d... (47 %)
> > Writing at 0x003aa5a2... (48 %)
> > Writing at 0x003af295... (49 %)
> > Writing at 0x003b42eb... (50 %)
> > Writing at 0x003b9442... (50 %)
> > Writing at 0x003be4f3... (51 %)
> > Writing at 0x003c35e4... (52 %)
> > Writing at 0x003c86d2... (53 %)
> > Writing at 0x003cceef... (53 %)
> > Writing at 0x003d1805... (54 %)
> > Writing at 0x003d6366... (55 %)
> > Writing at 0x003daec8... (56 %)
> > Writing at 0x003dfb96... (56 %)
> > Writing at 0x003e46ef... (57 %)
> > Writing at 0x003e9202... (58 %)
> > Writing at 0x003edbc4... (59 %)
> > Writing at 0x003f264e... (60 %)
> > Writing at 0x003f6fd2... (60 %)
> > Writing at 0x003fbad7... (61 %)
> > Writing at 0x0040077d... (62 %)
> > 找到无效库在 H:\Arduino\libraries\esp32_SoundRecorder: no headers files (.h) found in H:\Arduino\libraries\esp32_SoundRecorder
> > Writing at 0x00405341... (63 %)
> > Writing at 0x00409c1c... (63 %)
> > Writing at 0x0040e6a5... (64 %)
> > Writing at 0x00413152... (65 %)
> > Writing at 0x00417cbc... (66 %)
> > Writing at 0x0041cb08... (66 %)
> > Writing at 0x00421b4a... (67 %)
> > Writing at 0x00426cd2... (68 %)
> > Writing at 0x0042bb2d... (69 %)
> > Writing at 0x004309a2... (70 %)
> > Writing at 0x00435777... (70 %)
> > Writing at 0x0043a4b8... (71 %)
> > Writing at 0x0043efbd... (72 %)
> > Writing at 0x00443d21... (73 %)
> > Writing at 0x00448c70... (73 %)
> > Writing at 0x0044d905... (74 %)
> > Writing at 0x004524d9... (75 %)
> > Writing at 0x00456f97... (76 %)
> > Writing at 0x0045ba90... (76 %)
> > Writing at 0x00461f6d... (77 %)
> > Writing at 0x00467e94... (78 %)
> > Writing at 0x0046ddf7... (79 %)
> > Writing at 0x00473e4d... (80 %)
> > Writing at 0x0047a103... (80 %)
> > Writing at 0x004804b3... (81 %)
> > Writing at 0x004866de... (82 %)
> > Writing at 0x0048c974... (83 %)
> > Writing at 0x00492a06... (83 %)
> > Writing at 0x004989ad... (84 %)
> > Writing at 0x0049e9a5... (85 %)
> > Writing at 0x004a4b81... (86 %)
> > Writing at 0x004aad2a... (86 %)
> > Writing at 0x004b0e78... (87 %)
> > Writing at 0x004b7114... (88 %)
> > Writing at 0x004bd2b2... (89 %)
> > Writing at 0x004c33e2... (90 %)
> > Writing at 0x004c95d7... (90 %)
> > Writing at 0x004cf6f7... (91 %)
> > Writing at 0x004d5a62... (92 %)
> > Writing at 0x004dbef0... (93 %)
> > Writing at 0x004e22b9... (93 %)
> > Writing at 0x004e92b2... (94 %)
> > Writing at 0x004efc70... (95 %)
> > Writing at 0x004f6719... (96 %)
> > Writing at 0x004ff64b... (96 %)
> > Writing at 0x0050778b... (97 %)
> > Writing at 0x00510bfe... (98 %)
> > Writing at 0x005227e6... (99 %)
> > Writing at 0x0053225c... (100 %)
> > Wrote 5292032 bytes (2127378 compressed) at 0x00281000 in 46.6 seconds (effective 908.3 kbit/s)...
> > Hash of data verified.
> 
> Leaving... Hard resetting via RTS pin... 运行
> 
> > Build:Mar 27 2021
> > rst:0x15 (USB_UART_CHIP_RESET),boot:0x2b (SPI_FAST_FLASH_BOOT)
> > Saved PC:0x40378b31
> > SPIWP:0xee
> > mode:DIO, clock div:1
> > load:0x3fcd0108,len:0x178c
> > load:0x403b6000,len:0xe28
> > load:0x403ba000,len:0x30b8
> > entry 0x403b6274
> > �[0;32mI (28) boot: ESP-IDF v4.4 2nd stage bootloader�[0m
> > �[0;32mI (28) boot: compile time 16:32:36�[0m
> > �[0;32mI (28) boot: chip revision: 0�[0m
> > �[0;32mI (29) qio_mode: Enabling default flash chip QIO�[0m
> > �[0;32mI (35) boot.esp32s3: Boot SPI Speed : 80MHz�[0m
> > �[0;32mI (39) boot.esp32s3: SPI Mode       : QIO�[0m
> > �[0;32mI (44) boot.esp32s3: SPI Flash Size : 8MB�[0m
> > �[0;32mI (49) boot: Enabling RNG early entropy source...�[0m
> > �[0;32mI (54) boot: Partition Table:�[0m
> > �[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length�[0m
> > �[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00005000�[0m
> > �[0;32mI (72) boot:  1 otadata          OTA data         01 00 0000e000 00002000�[0m
> > �[0;32mI (80) boot:  2 factory          factory app      00 00 00010000 00271000�[0m
> > �[0;32mI (87) boot:  3 model            Unknown data     01 82 00281000 0050c000�[0m
> > �[0;32mI (95) boot: End of partition table�[0m
> > �[0;32mI (99) boot: Defaulting to factory image�[0m
> > �[0;32mI (104) esp_image: segment 0: paddr=00010020 vaddr=3c070020 size=26dd0h (159184) map�[0m
> > �[0;32mI (136) esp_image: segment 1: paddr=00036df8 vaddr=3fc97290 size=02a44h ( 10820) load�[0m
> > �[0;32mI (139) esp_image: segment 2: paddr=00039844 vaddr=40374000 size=067d4h ( 26580) load�[0m
> > �[0;32mI (147) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=66a2ch (420396) map�[0m
> 
> [16:43:00.246]收←◆�[0;32mI (214) esp_image: segment 4: paddr=000a6a54 vaddr=4037a7d4 size=0cab0h ( 51888) load�[0m �[0;32mI (225) esp_image: segment 5: paddr=000b350c vaddr=50000000 size=00010h ( 16) load�[0m �[0;32mI (232) boot: Loaded app from partition at offset 0x10000�[0m �[0;32mI (232) boot: Disabling RNG early entropy source...�[0m [ 252][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled Initializing SPIFFS
> 
> [16:43:00.633]收←◆Partition size: total: 4857101, used: 2629225
> 
> [16:43:00.679]收←◆model_name: xiaoaitongxue7q8 model_data: /srmodel/xiaoaitongxue7q8/wn7q8_data
> 
> [16:43:01.513]收←◆MC Quantized-8 wakeNet7: wakeNet7Q8_v1_xiaoaitongxue_5_0.97_0.90, mode:2, p:3, (Jan 5 2022 11:31:01) Initial ONE-MIC auido front-end for speech recognition, mode:0, (Dec 10 2021 11:08:01)
> 
> [16:43:04.129]收←◆------------detect start------------
> 
> [16:44:06.602]收←◆wakeword detected -----------LISTENING-----------
> 
> [16:44:17.908]收←◆ -----------awaits to be waken up----------- 请问这会是什么问题导致的呢？



> [16:43:01.513]收←◆MC Quantized-8 wakeNet7: wakeNet7Q8_v1_xiaoaitongxue_5_0.97_0.90, mode:2, p:3, (Jan 5 2022 11:31:01)
> Initial ONE-MIC auido front-end for speech recognition, mode:0, (Dec 10 2021 11:08:01)

**Comment by feizi** [comment]
◆MC Quantized-8 wakeNet7: wakeNet7Q8_v1_xiaoaitongxue_5_0.97_0.90, mode:2, p:3, (Jan 5 2022 11:31:01) ，这个是唤醒词初始化话
Initial ONE-MIC auido front-end for speech recognition, mode:0, (Dec 10 2021 11:08:01)， 这个是音频前端初始化

**Comment by tangjie133** [comment]
将他配置为中文但是他去输出了英文得命令词

>
![image](https://user-images.githubusercontent.com/51323906/179481045-ddc285a5-624f-42c5-bfb3-d0c59b212dd8.png)
