### ISSUE TITLE
Example compile failed, (examples/voice_communication) (AIS-948)

### ISSUE THREAD

**Issue by EeeeBin** [espressif/esp-skainet#57]
Env: 
    idf: v4.4 master
    esp-skainet: master branch, d566965b8f61073ea583f4ca365316a77cdc2bcb
Borad:
    esp32s3-box
Error:
![image](https://user-images.githubusercontent.com/24584225/183549927-11051c9c-eccc-4cc3-8ec4-d1f93f8bca2f.png)

This problem occurs when updating the esp-sr repository, libesp_audio_processor.a has to depend on esp-dsp, the link is not added in cmake

**Comment by feizi** [comment]
Hi @EeeeBin ,
The esp-dsp.a has been added, please try again.
