### ISSUE TITLE
在chinese_tts的example中，我无法找到"esp_audio_play()"有关这个函数的任何信息 (AIS-954)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-skainet#59]
在./example/chinese_tts/main/main.c中第76行，esp_audio_play(pcm_data, len[0]*2, portMAX_DELAY);  我翻遍了[esp-skainet]中所有的头文件，但是仍然找不到esp_audio_play()这个定义。我想知道这个函数是如何定义以及作用，谢谢！

**Comment by feizi** [comment]
在 ./components/hardware_driver/include/esp_board_init.h
https://github.com/espressif/esp-skainet/blob/master/components/hardware_driver/include/esp_board_init.h#:~:text=esp_err_t%20esp_audio_play(const%20int16_t*%20data%2C%20int%20length%2C%20TickType_t%20ticks_to_wait)%3B
