### ISSUE TITLE
Have we released the sound source localization API yet? (AIS-959)

### ISSUE THREAD

**Issue by sm4llb0y** [espressif/esp-skainet#61]
Hey Skainet team,

Thanks a lot for this great project first.

I remembered that we made a promise that we'll release corresponding sound source localization API for esp32-korvo, do we have that API now?

Best regards,
Arthur

**Comment by feizi** [comment]
Not yet.
We put more effort into optimizing the dual-mic algorithm, so the priority of the sound source localization algorithm decreased.

**Comment by sm4llb0y** [comment]
Copy that, really appreciate your quick response, and good luck with the current optimizations and looking forward other new features planned ahead!

Keep going and good luck!
- Arthur
