### ISSUE TITLE
Configuration incomplete, errors occurred! (AIS-964)

### ISSUE THREAD

**Issue by todd2023** [espressif/esp-skainet#62]
trying to run en_speech_commands_recognition example and got the following error: Configuration incomplete, error occurred!

I tried-> idf.py set-target esp32s3
error in build.cmake:227
where would be a good place to locate error?
please help

**Comment by feizi** [comment]
please try to replace sdkconfig with sdkconfig.defaults.esp32s3 and rebuild 
```
idf.py clean
cp sdkconfig.defaults.esp32s3 sdkconfig
idf.py flash monitor
```
