### ISSUE TITLE
ESP-32-S3-EYE使用cn_speech_commands_recognition不能够识别 (AIS-1016)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-skainet#66]
步骤1.idf.py set-target esp32s3
步骤2：cp  sdkconfig.defaults.esp32s3eye sdkconfig
步骤3：编译上传
成功上传之后不能够识别，但是在esp-who下是可以识别的。
我发现ESP-32S3-EYE下的AFE默认的是total channel: 3, mic num: 2, ref num: 1，但ESP-32S3-EYE是单麦，于是我就修改成了total channel: 2, mic num: 1, ref num: 1
但是修改成这样程序就会跑飞。
下面是log

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x1794
load:0x403b6000,len:0xe0c
load:0x403ba000,len:0x3068
entry 0x403b626c
I (24) boot: ESP-IDF v4.4-dirty 2nd stage bootloader
I (24) boot: compile time 11:08:06
I (24) boot: chip revision: 0
I (26) qio_mode: Enabling default flash chip QIO
I (31) boot.esp32s3: Boot SPI Speed : 80MHz
I (36) boot.esp32s3: SPI Mode       : QIO
I (41) boot.esp32s3: SPI Flash Size : 8MB
W (46) boot.esp32s3: PRO CPU has been reset by WDT.
W (51) boot.esp32s3: APP CPU has been reset by WDT.
I (57) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (66) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 factory          factory app      00 00 00010000 00200000
I (80) boot:  1 model            Unknown data     01 82 00210000 0050c000
I (88) boot: End of partition table
I (92) esp_image: segment 0: paddr=00010020 vaddr=3c080020 size=2e950h (190800) map
I (129) esp_image: segment 1: paddr=0003e978 vaddr=3fca0b40 size=016a0h (  5792) load
I (131) esp_image: segment 2: paddr=00040020 vaddr=42000020 size=787e4h (493540) map
I (210) esp_image: segment 3: paddr=000b880c vaddr=3fca21e0 size=039b0h ( 14768) load
I (213) esp_image: segment 4: paddr=000bc1c4 vaddr=40378000 size=18b34h (101172) load
I (235) esp_image: segment 5: paddr=000d4d00 vaddr=50000000 size=00010h (    16) load
I (245) boot: Loaded app from partition at offset 0x10000
I (246) boot: Disabling RNG early entropy source...
I (246) opi psram: vendor id : 0x0d (AP)
I (250) opi psram: dev id    : 0x02 (generation 3)
I (256) opi psram: density   : 0x03 (64 Mbit)
I (261) opi psram: good-die  : 0x01 (Pass)
I (266) opi psram: Latency   : 0x01 (Fixed)
I (270) opi psram: VCC       : 0x01 (3V)
I (275) opi psram: SRF       : 0x01 (Fast Refresh)
I (280) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (286) opi psram: BurstLen  : 0x01 (32 Byte)
I (291) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (297) opi psram: DriveStrength: 0x00 (1/1)
W (302) PSRAM: DO NOT USE FOR MASS PRODUCTION! Timing parameters will be updated in future IDF version.
I (313) spiram: Found 64MBit SPI RAM device
I (317) spiram: SPI RAM mode: sram 80m
I (321) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (328) cpu_start: Pro cpu up.
I (332) cpu_start: Starting app cpu, entry point is 0x403793d0
0x403793d0: call_start_cpu1 at D:/Users/34010/.espressif/frameworks/esp-idf-v4.4/components/esp_system/port/cpu_start.c:156

I (0) cpu_start: App cpu up.
I (627) spiram: SPI SRAM memory test OK
I (636) cpu_start: Pro cpu start user code
I (636) cpu_start: cpu freq: 240000000
I (636) cpu_start: Application information:
I (636) cpu_start: Project name:     speech_commands_recognition
I (636) cpu_start: App version:      1
I (636) cpu_start: Compile time:     Oct 24 2022 11:06:24
I (637) cpu_start: ELF file SHA256:  068266a08b4eeaec...
I (637) cpu_start: ESP-IDF:          v4.4-dirty
I (637) heap_init: Initializing. RAM available for dynamic allocation:
I (637) heap_init: At 3FCA7C10 len 000383F0 (224 KiB): D/IRAM
I (637) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (638) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (638) spiram: Adding pool of 8192K of external SPI memory to heap allocator
I (639) spi_flash: detected chip: generic
I (639) spi_flash: flash io: qio
I (640) sleep: Configure to isolate all GPIO pins in sleep state
I (640) sleep: Enable automatic switching of GPIO sleep configuration
I (640) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (641) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (641) MODEL_LOADER:
Initializing models from SPIFFS, partition label: model

I (961) MODEL_LOADER: Partition size: total: 4857101, used: 2085308

I (1231) I2S: DMA Malloc info, datalen=blocksize=640, dma_buf_count=6
I (1231) AFE_SR: afe interface for speech recognition

I (1231) AFE_SR: AFE version: SR_V220727

I (1231) AFE_SR: Initial auido front-end, total channel: 2, mic num: 1, ref num: 1

I (1231) AFE_SR: aec_init: 0, se_init: 1, vad_init: 1

I (1231) AFE_SR: wakenet_init: 1

model_name: wn9_hilexin model_data: /srmodel/wn9_hilexin/wn9_data
MC Quantized wakenet9: wakenet9_v1h24_hilexin_3_0.608_0.615, tigger:v3, mode:2, p:1, (Sep  8 2022 20:07:38)
I (1951) AFE_SR: wake num: 2, mode: 0, (Sep  8 2022 20:14:30)

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)
Saved PC:0x42003585
0x42003585: panic_handler at D:/Users/34010/.espressif/frameworks/esp-idf-v4.4/components/esp_system/port/panic_handler.c:148 (discriminator 3)

所以我应该怎么做而使得ESP-32-S3-EYE可以成功运行在skainet呢？
谢谢

**Comment by feizi** [comment]
The noise suppression module of 1mic is enabled by default and requires more stack memory for i2s feed task.
