### ISSUE TITLE
ESP32-S3-Korvo-1 V5.0 运行cn_speech_commands_recognition，复位问题 (AIS-1040)

### ISSUE THREAD

**Issue by zxg623** [espressif/esp-skainet#73]
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2b (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x1854
load:0x403b6000,len:0xb74
load:0x403ba000,len:0x3014
entry 0x403b61ec
I (25) boot: ESP-IDF v4.4-beta1-2-gdf0929009a 2nd stage bootloader
I (25) boot: compile time 11:30:57
I (25) boot: chip revision: 0
I (28) qio_mode: Enabling default flash chip QIO
I (33) boot.esp32s3: Boot SPI Speed : 80MHz
I (38) boot.esp32s3: SPI Mode       : QIO
I (43) boot.esp32s3: SPI Flash Size : 16MB
I (48) boot: Enabling RNG early entropy source...
W (53) bootloader_random: RNG for ESP32-S3 not currently supported
I (60) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 factory          factory app      00 00 00010000 00200000
I (78) boot:  1 model            Unknown data     01 82 00210000 0050c000
I (86) boot: End of partition table
I (90) esp_image: segment 0: paddr=00010020 vaddr=3c080020 size=92010h (598032) map
I (189) esp_image: segment 1: paddr=000a2038 vaddr=3fca2bd0 size=0520ch ( 21004) load
I (193) esp_image: segment 2: paddr=000a724c vaddr=40378000 size=08dcch ( 36300) load
I (202) esp_image: segment 3: paddr=000b0020 vaddr=42000020 size=7f0b8h (520376) map
I (282) esp_image: segment 4: paddr=0012f0e0 vaddr=40380dcc size=11dfch ( 73212) load
I (296) esp_image: segment 5: paddr=00140ee4 vaddr=50000000 size=00010h (    16) load
I (307) boot: Loaded app from partition at offset 0x10000
I (307) boot: Disabling RNG early entropy source...
W (308) bootloader_random: RNG for ESP32-S3 not currently supported
I (326) opi psram: vendor id : 0x0d (AP)
I (326) opi psram: dev id    : 0x02 (generation 3)
I (326) opi psram: density   : 0x03 (64 Mbit)
I (330) opi psram: good-die  : 0x01 (Pass)
I (334) opi psram: Latency   : 0x01 (Fixed)
I (339) opi psram: VCC       : 0x01 (3V)
I (344) opi psram: SRF       : 0x01 (Fast Refresh)
I (349) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (355) opi psram: BurstLen  : 0x01 (32 Byte)
I (360) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (366) opi psram: DriveStrength: 0x00 (1/1)
W (371) PSRAM: DO NOT USE FOR MASS PRODUCTION! Timing parameters will be updated in future IDF version.
I (381) spiram: Found 64MBit SPI RAM device
I (386) spiram: SPI RAM mode: sram 80m
I (390) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (397) cpu_start: Pro cpu up.
I (401) cpu_start: Starting app cpu, entry point is 0x4037955c
0x4037955c: call_start_cpu1 at D:/STM32F030F4/esp/esp-idf/esp-skainet/esp-skainet/esp-idf/components/esp_system/port/cpu_start.c:156

I (0) cpu_start: App cpu up.
I (696) spiram: SPI SRAM memory test OK
W (696) rtcinit: calibration efuse version does not match, set default version: 0

I (708) cpu_start: Pro cpu start user code
I (708) cpu_start: cpu freq: 240000000
I (708) cpu_start: Application information:
I (711) cpu_start: Project name:     speech_commands_recognition
I (718) cpu_start: App version:      v0.3.0-137-gaa36390-dirty
I (724) cpu_start: Compile time:     Nov 18 2022 11:30:41
I (730) cpu_start: ELF file SHA256:  345501c6b66d9801...
I (736) cpu_start: ESP-IDF:          v4.4-beta1-2-gdf0929009a
I (743) heap_init: Initializing. RAM available for dynamic allocation:
I (750) heap_init: At 3FCA9F18 len 000360E8 (216 KiB): D/IRAM
I (756) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (763) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (769) spiram: Adding pool of 8192K of external SPI memory to heap allocator
I (777) spi_flash: detected chip: gd
I (781) spi_flash: flash io: qio
I (786) sleep: Configure to isolate all GPIO pins in sleep state
I (792) sleep: Enable automatic switching of GPIO sleep configuration
I (799) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (830) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (830) MODEL_LOADER: 
Initializing models from SPIFFS, partition label: model

I (1160) MODEL_LOADER: Partition size: total: 4857101, used: 2085308

I (1420) I2S: DMA Malloc info, datalen=blocksize=1280, dma_buf_count=6
I (1420) I2S: I2S1, MCLK output by GPIO20
I (1420) I2S: DMA Malloc info, datalen=blocksize=320, dma_buf_count=6
I (1430) I2S: I2S0, MCLK output by GPIO42
I (1440) board: Detected codec at 0x40. Name : ES7210
I (1440) board: Detected codec at 0x18. Name : ES8311
I (1460) ES7210: ES7210 in Slave mode
I (1460) ES7210: Enable ES7210_INPUT_MIC1
I (1460) ES7210: Enable ES7210_INPUT_MIC2
I (1460) ES7210: Enable ES7210_INPUT_MIC3
I (1470) ES7210: Enable ES7210_INPUT_MIC4
I (1480) ES7210: The ES7210_CLOCK_OFF_REG01 value before stop is 0
I (1480) ES7210: Enable ES7210_INPUT_MIC1
I (1480) ES7210: Enable ES7210_INPUT_MIC2
I (1490) ES7210: Enable ES7210_INPUT_MIC3
I (1490) ES7210: Enable ES7210_INPUT_MIC4
I (1500) DRV8311: ES8311 in Slave mode
I (1510) gpio: GPIO[38]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (1510) AFE_SR: afe interface for speech recognition

I (1520) AFE_SR: AFE version: SR_V220727

I (1520) AFE_SR: Initial auido front-end, total channel: 3, mic num: 2, ref num: 1

I (1530) AFE_SR: aec_init: 1, se_init: 1, vad_init: 1

I (1530) AFE_SR: wakenet_init: 1

model_name: wn9_hilexin model_data: /srmodel/wn9_hilexin/wn9_data
MC Quantized wakenet9: wakenet9_v1h24_hilexin_3_0.608_0.615, tigger:v3, mode:2, p:0, (Oct  9 2022 17:21:08)
I (2440) AFE_SR: wake num: 3, mode: 0, (Oct 12 2022 19:13:45)

multinet:mn4_cn
I (2440) MN: model_name: mn4_cn model_data: /srmodel/mn4_cn/mn4_cn_data
I (4560) MN: SINGLE_RECOGNITION: V4.5 CN; core: 0; (Oct 12 2022 19:13:44)

esp_mn_commands_update_from_sdkconfig
I (4560) MN_COMMAND: ---------------------SPEECH COMMANDS---------------------
I (4570) MN_COMMAND: Command ID0, phrase ID0: da kai kong tiao
I (4570) MN_COMMAND: Command ID1, phrase ID1: guan bi kong tiao
I (4580) MN_COMMAND: Command ID2, phrase ID2: zeng da feng su
I (4590) MN_COMMAND: Command ID3, phrase ID3: jian xiao feng su
I (4590) MN_COMMAND: Command ID4, phrase ID4: sheng gao yi du
I (4600) MN_COMMAND: Command ID5, phrase ID5: jiang di yi du
I (4610) MN_COMMAND: Command ID6, phrase ID6: zhi re mo shi
I (4610) MN_COMMAND: Command ID6, phrase ID7: zhi le mo shi
I (4620) MN_COMMAND: Command ID7, phrase ID8: zhi leng mo shi
I (4630) MN_COMMAND: Command ID7, phrase ID9: zhi ren mo shi
I (4630) MN_COMMAND: Command ID7, phrase ID10: zhi len mo shi
I (4640) MN_COMMAND: Command ID8, phrase ID11: jie neng mo shi
I (4640) MN_COMMAND: Command ID9, phrase ID12: guan bi jie neng mo shi
I (4650) MN_COMMAND: Command ID10, phrase ID13: chu shi mo shi
I (4660) MN_COMMAND: Command ID11, phrase ID14: guan bi chu shi mo shi
I (4670) MN_COMMAND: Command ID12, phrase ID15: shui mian mo shi
I (4670) MN_COMMAND: Command ID13, phrase ID16: guan bi shui mian mo shi
I (4680) MN_COMMAND: Command ID14, phrase ID17: ding shi yi xiao shi
I (4690) MN_COMMAND: Command ID15, phrase ID18: ding shi liang xiao shi
I (4690) MN_COMMAND: Command ID16, phrase ID19: zui da feng su
I (4700) MN_COMMAND: Command ID16, phrase ID20: zui gao feng su
I (4710) MN_COMMAND: ---------------------------------------------------------

------------detect start------------
WAKEWORD DETECTED
AFE_FETCH_CHANNEL_VERIFIED, channel index: 2

assert failed: dl_matrixq_slice dl_lib_matrixq.c:483 (in->flags & DL_MF_FOREIGNDATA)

Backtrace:0x40379e86:0x3fce96b00x4038a3ad:0x3fce96d0 0x40390961:0x3fce96f0 0x420212da:0x3fce9810 0x42022e1e:0x3fce9830 0x42021e5e:0x3fce9890 0x420153cb:0x3fce98c0 0x42015a4b:0x3fce98f0 0x4200789e:0x3fce9910 0x4038d51d:0x3fce9940
0x40379e86: panic_abort at D:/STM32F030F4/esp/esp-idf/esp-skainet/esp-skainet/esp-idf/components/esp_system/panic.c:402

0x4038a3ad: esp_system_abort at D:/STM32F030F4/esp/esp-idf/esp-skainet/esp-skainet/esp-idf/components/esp_system/esp_system.c:121

0x40390961: __assert_func at D:/STM32F030F4/esp/esp-idf/esp-skainet/esp-skainet/esp-idf/components/newlib/assert.c:85

0x420212da: dl_matrixq_slice at /home/sunxiangyu/aishare/master/esp_sr_lib/build/../components/dl_lib/dl_lib_matrixq.c:483

0x42022e1e: dl_convq16_lstm_layer_s3 at /home/sunxiangyu/aishare/master/esp_sr_lib/build/../components/dl_lib/dl_lib_convq_queue_s3.c:960 (discriminator 2)

0x42021e5e: dl_convq16_lstm_layer at /home/sunxiangyu/aishare/master/esp_sr_lib/build/../components/dl_lib/dl_lib_convq_queue.c:620

0x420153cb: multinet4_model_run_step2 at /home/sunxiangyu/aishare/master/esp_sr_lib/build/../components/multinet/multinet4_single_quantized_cn.c:1141

0x42015a4b: model_detect at /home/sunxiangyu/aishare/master/esp_sr_lib/build/../components/multinet/multinet4_single_quantized_cn.c:1607

0x4200789e: detect_Task at D:\STM32F030F4\esp\esp-idf\esp-skainet\esp-skainet\examples\cn_speech_commands_recognition\build/../main/main.c:115

0x4038d51d: vPortTaskWrapper at D:/STM32F030F4/esp/esp-idf/esp-skainet/esp-skainet/esp-idf/components/freertos/port/xtensa/port.c:130

**Comment by feizi** [comment]
Please update esp-sr component to latest commit.
