### ISSUE TITLE
使用自己画的esp32s3开发板运行wake_word_detection遇到问题 (AIS-1046)

### ISSUE THREAD

**Issue by Letian-stu** [espressif/esp-skainet#75]
你好，我在使用模块是esp32s3,使用的麦克风和eye的板子一样，在开启CONFIG_ESP32_S3_EYE_BOARD的配置，然后修改了components\hardware_driver\boards\include\esp32_s3_eye_board.h中iis的引脚，然后可以直接烧入使用嘛？还是说还需要修改其他地方。我试了试运行后log显示，------------detect start------------，然后说唤醒口令也没反应。

**Comment by BlueSkyB** [comment]
EYE的板子，需要根据实际的音频，配置音频的通道数。
最新的example，针对EYE，已经添加了这个配置(EYE的板子，esp_get_feed_data获取到的是两通道数据)，可以更新下code：
afe_config.pcm_config.total_ch_num = 2;
afe_config.pcm_config.mic_num = 1;
afe_config.pcm_config.ref_num = 1;

如果还不行，需要你先确认下I2S获取的音频是正常的。然后根据实际音频，配置上面三个配置。具体说明可参考：https://github.com/espressif/esp-sr/tree/654833db916476cd4b44d3fbf510ac57b44cfde6/docs/audio_front_end
