### ISSUE TITLE
Chinese_tts demo with MP3_demo. (AIS-1049)

### ISSUE THREAD

**Issue by babadue** [espressif/esp-skainet#76]
I have been trying to get the audio player from the MP3_DEMO (esp-box example) to work with the tts from the CHINESE_TTS (esp-skainet) demo without much success.

Can it be done?  Has anyone done it already?  Any pointers?

**Comment by feizi** [comment]
I think you should pay attention to the partition table. Chinese tts voice data is  quite large and must be carefully arranged.
