### ISSUE TITLE
自定义命令词说明连接失效 (AIS-1051)

### ISSUE THREAD

**Issue by imlsq** [espressif/esp-skainet#77]
自定义命令词说明连接失效
https://github.com/espressif/esp-sr/blob/master/docs/speech_command_recognition/README.md
打开后是404

**Comment by feizi** [comment]
我们正在更新文档系统，可以点击进入 esp-sr/docs 查看相关文档 
中文自定义命令词 请参考 https://github.com/espressif/esp-sr/tree/master/docs/zh_CN/speech_command_recognition
