### ISSUE TITLE
如何通过串口或网络添加/删除自定义命令词？ (AIS-1052)

### ISSUE THREAD

**Issue by imlsq** [espressif/esp-skainet#78]
看了例子和文档，都找不到资料。
这个功能才是重点，那种通过menuconfig配置命令词的方式没什么用。
需要在运行状态下动态删除和添加命令词的方式

**Comment by feizi** [comment]
你现在可以参考动态修改词的API： https://github.com/espressif/esp-sr/blob/master/src/esp_mn_speech_commands.c
我们后续会更新skainet中的例子，添加这部分的使用示例。

**Comment by Liuyuehuixue** [comment]
> 你现在可以参考动态修改词的API： https://github.com/espressif/esp-sr/blob/master/src/include/esp_mn_speech_commands.h 我们后续会更新skainet中的例子，添加这部分的使用示例。

在cn_speech_commands_recognition例子中main.c使用调用api方法是成功的
    esp_mn_commands_add(2, "guan bi kong tiao");  
    esp_mn_commands_add(3, "da kai kong tiao");  
    esp_mn_commands_update(); 
但是，在烧录完成之后，如何修改命令词呢？

**Comment by feizi** [comment]
这需要你通过Wi-Fi 或其他协议和板子进行通讯，将所需的命令词使用以上api进行更新

**Comment by Liuyuehuixue** [comment]
好的，非常感谢
