### ISSUE TITLE
关于唤醒时输出语音

### ISSUE THREAD

**Issue by Shaopus** [espressif/esp-skainet#8]
你好：

我测试了下，在garbage_classification的例子中，通过唤醒后，增加输出音频(**在的**)后，再用说出各个垃圾后，识别非常困难，经常无法识别？
```C         
if (r) {
	// wakenet_open(); /* 输出语音 “在的” */
        float ms = (chunks * audio_chunksize * 1000.0) / frequency;
        printf("%.2f: %s DETECTED.\n", (float)ms / 1000.0, wakenet->get_word_name(model_data, r));
        detect_flag = 1;
        printf("-----------------LISTENING-----------------\n\n");
        led_on(LED_GPIO);
}
```
请问**唤醒后，输出语音**，让用户知道唤醒 了，这种情况该怎么解决？

**Comment by WeldonWangwang** [comment]
@Shaopus Hi, 这个可能会有两点原因导致：
第一是播放的音频时，i2s buffer 有未被完全清空的风险；
第二是在播放音频时，mic 会采集到一些播放出的音频存在 ring buffer 里，所以在 wakent 和 multinet 切换时建议清空 ring buf

我们近期会根据您的反馈修改该 demo，也加入唤醒后的“我在”提示音，并且更新 MultiNet 的版本，后续您也可以参考此 demo.
