### ISSUE TITLE
Adjust the time between wakeword detected and timeout (AIS-1062)

### ISSUE THREAD

**Issue by babadue** [espressif/esp-skainet#81]
How do you adjust the time between WAKENET_DETECTED and ESP_MN_STATE_TIMEOUT?

**Comment by babadue** [comment]
> When you create multinet model, like this `multinet->create(mn_name, time_ms)` The second parameter is the time in milliseconds of ESP_MN_STATE_TIMEOUT.

Wow, I missed that magic 5760 number!  
谢了.

**Comment by PrathamG** [comment]
Hi! I had a related question, what if I needed the multinet to run indefinitely after the wakeword is detected. What do I provide as the time_ms parameter if I want the multinet to keep running forever?
