### ISSUE TITLE
Wake-World Broken link  (AIS-1067)

### ISSUE THREAD

**Issue by Na2l** [espressif/esp-skainet#82]
[Espressif Speech Wake Words Customization Process](https://github.com/espressif/esp-sr/blob/master/docs/wake_word_engine/ESP_Wake_Words_Customization.md).

is broken.

can someone tell me how I can create my own Wake-Words?

**Comment by Sandra-lol** [comment]
Hi, please check the doc here: https://docs.espressif.com/projects/esp-sr/en/latest/esp32/wake_word_engine/ESP_Wake_Words_Customization.html
The links will be renewed soon in Github.
