### ISSUE TITLE
Help with ESP32 Korvo 1 v5.0 (AIS-1068)

### ISSUE THREAD

**Issue by imdahsiaria90** [espressif/esp-skainet#83]
I newly bought the ESP32 Korvo-1 v5.0 development board. I have installed the latest release from [https://github.com/espressif/esp-skainet]

I flashed the example "en_speech_commands_recognition"

Observation/ Question:

1. There is hardly any documentation on the example. Where can I find this ?
3. Audio does not seem to work. I have tried with both the headphones and speaker.
4. Is there any example on how to use the multinet commands in the code once they are detected ? 
5. Where can I find the source code of the default firmware ?

Help would highly be appreciated.

**Comment by Sandra-lol** [comment]
Hi, for en speech command recog, ESP32-S3 boards are recommended:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/42029442/210523469-4d4032c0-1f1d-4c66-9339-4ac3529f410e.png">

**Comment by imdahsiaria90** [comment]
Hello Sandra,

As mentioned in my description, I am using ESP32-S3-Korvo-1 v5.0.

**Comment by feizi** [comment]
Hi imdahsiaria90,
en_speech_commands_recognition example do not play any audio.
If you want play audio, you can refer to cn_speech_commands_recognition or [esp-box/factory_demo](https://github.com/espressif/esp-box/tree/master/examples/factory_demo)

**Comment by imdahsiaria90** [comment]
Hi Feizi.

OK thank you for the feedback. Atleast that solves for my question no 2.

Can you also provide any feedback on other questions ?

**Comment by feizi** [comment]
Please create new one if you have
