### ISSUE TITLE
IDF v5.0 support (AIS-1079)

### ISSUE THREAD

**Issue by nikhil-robinson** [espressif/esp-skainet#86]
Hey there,

Will esp-skainet be supported on latest idf v5 i am planing to migrate to 5.0, it would be helpful if someone could shed some light on this.

Thank you.

**Comment by feizi** [comment]
OK, we plan to support idf v5 next month.

**Comment by nikhil-robinson** [comment]
Sounds great!! Thanks for the reply!!!
