### ISSUE TITLE
ESP32-S3-WROOM-1 的板子语音唤醒没反应 (AIS-1136)

### ISSUE THREAD

**Issue by waruqi** [espressif/esp-skainet#90]
我看到当前这个项目的 hardware_driver 里面没有 ESP32-S3-WROOM-1 的驱动适配。。怎么才能支持 ESP32-S3-WROOM-1 的 MIC 呢？

当前现有支持的板子驱动中，哪个跟它比较接近，我可以参考着改改。

**Comment by tieppm** [comment]
> 我切到 s3-eye 的板子驱动就可以了。。应该都是数字麦克风

hello, can you share it?
I'm also using SP32-S3-WROOM-1
Thank you very much
