### ISSUE TITLE
FAILED: wake_word_detection.elf (AIS-1158)

### ISSUE THREAD

**Issue by ChenadSH** [espressif/esp-skainet#92]
用的idf 4.4.4编译报错如下，请问可能是什么原因呀

PS E:\esp32s3\esp-skainet\examples\wake_word_detection> idf.py build
Executing action: all (aliases: build)
Running ninja in directory e:\esp32s3\esp-skainet\examples\wake_word_detection\build
Executing "ninja all"...
[1/6] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D E:\esp32s3\esp-skainet\examples\wake_word_detection\build\bootloader\esp-idf\esptool_py && D:\software\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe D:/software/Espressif/frameworks/esp-idf-v4.4.4/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x0 E:/esp32s3/esp-skainet/examples/wake_word_detection/build/bootloader/bootloader.bin"
Bootloader binary size 0x57a0 bytes. 0x2860 bytes (32%) free.
[2/4] Linking CXX executable wake_word_detection.elf
FAILED: wake_word_detection.elf
cmd.exe /C "cd . && D:\software\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-g++.exe -mlongcalls  @CMakeFiles\wake_word_detection.elf.rsp -o wake_word_detection.elf  && cd ."
d:/software/espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: E:/esp32s3/esp-skainet/components/esp-sr/lib/esp32s3/libesp_audio_front_end.a(esp_afe_sr.c.obj):(.literal.afe_destory+0x14): undefined reference to `sr_rb_abort'
d:/software/espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: E:/esp32s3/esp-skainet/components/esp-sr/lib/esp32s3/libesp_audio_front_end.a(esp_afe_sr.c.obj):(.literal.afe_destory+0x20): undefined reference to `dl_lib_free'
d:/software/espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: 
........
d:/software/espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: /home/sunxiangyu/aishare/master/esp_sr_lib/build/../components/hufzip/hufzip_model.c:376: undefined reference to `dl_lib_free'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by feizi** [comment]
请更新esp-sr到master，看看能不能解决这个问题
